name: Python Checks

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test_runner:
        name: "Test Runner"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.12.0
            - name: Install dependencies
              run: |
                cd backend
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv install --dev
            - name: Test with pytest
              run: |
                    cd backend
                    pipenv run pytest -p no:warnings
